bun run ncd-pair-repo ..\zeeguu-web json "**/*.*"
bun run ncd-pair-repo ..\zeeguu-api json "**/*.*"
bun run ncd-pair-repo ..\git-truck json "**/*.*"
bun run ncd-pair-repo ..\bong-maps json "**/*.*"
bun run ncd-pair-repo ..\linux json "**/*.rs"
bun run ncd-pair-repo ..\sqlite json "**/*.*"
