on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build .
  test-usage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          input_path: docs/index.md
          output_dir: generated
          build_html: false
      - uses: actions/upload-artifact@v4
        with:
          name: readme
          path: generated
